### ISSUE TITLE
Experimental UI update

### ISSUE THREAD

**Issue by hiesterd** [City-of-Bloomington/meter_monitor#9]
As a new member of the ITS team, I'd like to assess an opportunity to improve the look and feel of our internal apps, starting with a recently-shipped app. The Meter Monitor is an interesting opportunity for this, because there may be benefit in implementing a responsive design that can be used in the field on iPhones.

**Comment by inghamn** [comment]
The UI changes were merged in from the branch.  If there are more UI changes necessary, they can be addressed in specific future issues.
